import { SlashCommandBuilder } from 'discord.js';

const pingCommand = new SlashCommandBuilder()
  .setName('help')
  .setDescription('How to use Bramdroid');

export const data = pingCommand;

export async function execute(interaction) {
  await interaction.reply(`**Bramdroid** is a Discord bot that helps you find quotes from books. It's powered by the [Quoordinates](https://github.com/bramses/quoordinates) API, which is a semantic search engine for quotes from books. Slash Commands:
- \`/duel\` - Find quotes based on your responses to two prompts. Topics are surfaced from Quoordinates and follow up questions are generated by the OpenAI API. Costs 1 \`/duel\` credit.
- \`/quos\` - Find quotes based on your search query. If you don't know what to search, try the \`/duel\` or the \`/random\` commands. Costs 1 \`/quos\` credit.
- \`/random\` - Fetch a random quote from the library. Costs 1 \`/random\` credit.
Buttons:
- \`aart\` - Creates an abstract image based on the quote. Costs 1 \`aart\` credit.
- \`delve\` - Delve deeper into the quotes main ideas, explore its neighbors. Costs 1 \`delve\` credit.
- \`tldr\` - Summarize the quote. Costs 1 \`tldr\` credit.
- \`share\` - Share the quote by overlaying the quote text onto an \`aart\` creation. Every time is unique! Costs 1 \`share\` credit.
- \`repost\` - Repost the quote to a more fitting channel. Costs 1 \`repost\` credit. Only available from the \`/random\` command.

React to any message with the floppy disk emoji (💾, : floppy_disk : (no spaces)) to save the quote to your personal library.

Bramdroid is open source! You can see the bot [source code here](https://github.com/bramses/bramdroid)`);
}